// Generated by CoffeeScript 1.12.7
(function() {
  var $, Chrome, Dir, File, Process, _, addTab, bindKey, hideTabs, ref, showTabs, switchToTab;

  $ = require('jquery');

  _ = require('underscore');

  ref = require('osx'), Chrome = ref.Chrome, File = ref.File, Dir = ref.Dir, Process = ref.Process;

  bindKey = require('editor').bindKey;

  $(document).delegate('#tabs ul li:not(.add) a', 'click', function() {
    switchToTab(this);
    return false;
  });

  $(document).delegate('#tabs .add a', 'click', function() {
    addTab();
    return false;
  });

  bindKey('toggleTabs', 'Command-Ctrl-T', function(env) {
    if ($('#tabs').length) {
      return hideTabs();
    } else {
      return showTabs();
    }
  });

  showTabs = function() {
    var css;
    Chrome.addPane('top', require('tabs/tabs.html'));
    $('#tabs').parents('.pane').css({
      height: 'inherit'
    });
    css = $('<style id="tabs-style"></style>').html(require('tabs/tabs.css'));
    return $('head').append(css);
  };

  hideTabs = function() {
    $('#tabs').parents('.pane').remove();
    return $('#tabs-style').remove();
  };

  addTab = function() {
    $('#tabs ul .add').before('<li><a href="#">untitled</a></li>');
    $('#tabs ul .active').removeClass();
    return $('#tabs ul .add').prev().addClass('active');
  };

  switchToTab = function(tab) {
    $('#tabs ul .active').removeClass();
    return $(tab).parents('li').addClass('active');
  };

  exports.show = exports.showTabs = showTabs;

  exports.hideTabs = hideTabs;

  exports.addTab = addTab;

  exports.switchToTab = switchToTab;

}).call(this);
