// Generated by CoffeeScript 1.12.7
(function() {
  var code, path, root;
  console.originalLog = console.log;

  console.log = function(thing) {
    if (thing != null) {
      //OSX.NSLog(thing);
    }
    return console.originalLog(thing);
  };

  root = OSX.NSBundle.mainBundle.resourcePath;

  code = OSX.NSString.stringWithContentsOfFile(path = root + "/src/require.js");

  __jsc__.evalJSString_withScriptPath(code, path);

  console.log('require tests:');

  console.log(require.resolve('underscore'));

  console.log(require.resolve('osx'));

  console.log(require.resolve('ace/requirejs/text!ace/css/editor.css'));

  console.log(require.resolve('ace/keyboard/keybinding'));

  console.log('--------------');

}).call(this);
