// Generated by CoffeeScript 1.12.7
(function() {
  var _, ace, modeForLanguage, modeMap, setMode;

  _ = require('underscore');

  ace = require('editor').ace;

  modeMap = {
    js: 'javascript',
    c: 'c_cpp',
    cpp: 'c_cpp',
    h: 'c_cpp',
    m: 'c_cpp',
    md: 'markdown',
    cs: 'csharp'
  };

  modeForLanguage = function(language) {
    var e, modeName;
    console.log("modeForLanguage(" + language + ")");
    language = language.toLowerCase();
    modeName = modeMap[language] || language;
    console.log("modeName: " + modeName);
    try {
      return require("ace/mode/" + modeName).Mode;
    } catch (error) {
      e = error;
      return null;
    }
  };

  setMode = function(arg) {
    var filename, mode;
    filename = arg.filename;
    console.log("setMode(" + filename + ")");
    if (mode = modeForLanguage(_.last(filename.split('.')))) {
      console.dir(mode);
      return ace.getSession().setMode(new mode);
    }
  };

  exports.init = function() {
    ace.on('open', setMode);
    return ace.on('save', setMode);
  };

  exports.modeMap = modeMap;

}).call(this);
