// Generated by CoffeeScript 1.12.7
(function() {
  var Document,
    slice = [].slice;

  Document = (function() {
    var open;

    Document.prototype.path = null;

    Document.prototype.text = null;

    Document.prototype.listeners = [];

    function Document(path, text) {
      this.path = path;
      this.text = text;
    }

    Document.prototype.name = function() {
      if (this.path) {
        return _.last(this.path.split('/'));
      }
    };

    Document.prototype.save = function() {
      return trigger('saved');
    };

    open = function() {
      return trigger('opened');
    };

    Document.prototype.on = function(message, listener) {
      return this.listeners.push(listener);
    };

    Document.prototype.trigger = function() {
      var args, message;
      message = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      return _.each(this.listeners, function(listener) {
        return listener.call.apply(listener, args);
      });
    };

    return Document;

  })();

}).call(this);
